config/routes.rb
Rails.application.routes.draw do

  root                      'static_pages#home'

  get 'about'           =>  'static_pages#about'

  get 'events'          =>  'static_pages#events'

  get 'groups'          =>  'static_pages#groups'

  get 'calendar'        =>  'static_pages#calendar'

  get 'contact'         =>  'static_pages#contact'

  get 'profile'         =>  'static_pages#profile'

  get 'signup'          =>  'users#new'

  devise_for :admins
  devise_for :users
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  #before_filter :cas_filter

  def cas_filter
    RubyCAS::Filter.filter self
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def events
  end

  def groups
  end

  def calendar
  end

  def contact
  end

  def profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
					<p class="copyright">Copyright &copy; 2015 - Edwin Agbenyega</p>
			</div>
		</div>
	</div>
	</div>

app/views/layouts/_header.html.erb
<!--Main Header-->
<header class="container-fluid" id="main_header" >
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-1">
      <h1 class="font-effect-shadow-multiple">Social Event Planner</h1>
      <h2 class="subtitle">The Social Event Planner App That Will Make Your Life at UNM More Than Fulfilling!</h2>
  			<div id="carousel-home" class="carousel slide" data-ride="carousel">
    			<ol class="carousel-indicators">
    				<li data-target="#carousel-home" data-slide-to="0" class="active"></li>
    				<li data-target="#carousel-home" data-slide-to="1"></li>
    				<li data-target="#carousel-home" data-slide-to="2"></li>
  			  </ol>
  			  <!-- slides -->
  			  <div class="carousel-inner" role="listbox">
    				<div class="item active">
              <%= image_tag "Banner1.jpg", alt:"" %>
    				</div>
    				<div class="item">
              <%= image_tag "Banner2.jpg", alt:"" %>
            </div>
    				<div class="item">
              <%= image_tag "Banner3.jpg", alt:"" %>
    				</div>
  			  </div>
          <!-- Left and right controls -->
          <a class="left carousel-control" href="#carousel-home" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-home" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
  			</div>
    </div>
    <div class="col-lg-3 col-lg-offset-1" id="signup_form">
      <div class="div-trans text-center">
        <h3> LOG IN </h3>
        <br>
        <div class="col-lg-12 col-md-12 col-sm-12" >

          <div class="form-group">
              <input type="text" class="form-control" required="required" placeholder="Username">
          </div>
          <div class="form-group">
              <input type="password" class="form-control" required="required" placeholder="Password">
          </div>
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block btn-lg">Log in</button>
          </div>
       </div>
     </div>
    </div>
  </div>
</header>

app/views/layouts/_homeheader.html.erb
<!--Main Header-->
<header class="container-fluid lg_header" >
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="row">
    <div class="col-lg-4 col-lg-offset-1">
      <h1 class: "font-effect-shadow-multiple">Social Event Planner</h1>
      <!--<h1 class="font-effect-shadow-multiple">Social Event Planner</h1>-->
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-lg-offset-1">
      <h3 class="subtitle">The Social Event Planner App That Will Make Your UNM Experience More Fulfilling!</h3>
    </div>
      <div class="col-lg-6 col-lg-offset-4">
  			<div id="carousel-home" class="carousel slide" data-ride="carousel">
    			<ol class="carousel-indicators">
    				<li data-target="#carousel-home" data-slide-to="0" class="active"></li>
    				<li data-target="#carousel-home" data-slide-to="1"></li>
    				<li data-target="#carousel-home" data-slide-to="2"></li>
  			  </ol>
  			  <!-- slides -->
  			  <div class="carousel-inner" role="listbox">
    				<div class="item active">
              <%= image_tag "car1.jpg", alt:"" %>
    				</div>
    				<div class="item">
              <%= image_tag "car2.jpg", alt:"" %>
            </div>
    				<div class="item">
              <%= image_tag "car3.jpg", alt:"" %>
    				</div>
  			  </div>
          <!-- Left and right controls -->
          <a class="left carousel-control" href="#carousel-home" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-home" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
  			</div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_nav.html.erb
<!--Navigation Bar-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <!--Navbar's collapsable toggle button for smaller devices-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Social Event Planner", root_path, class: "navbar-brand" %>
    </div>

    <!--Navbar's list-->
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "About",    about_path %></li>              <!--About-->
        <li><%= link_to "Events",   events_path %></li>             <!--Events-->
        <li><%= link_to "Groups",   groups_path %></li>             <!--Student Groups-->
        <li><%= link_to "Calendar", calendar_path %></li>           <!--Calendar-->
        <li><%= link_to "Contacts", contact_path %></li>            <!--Contacts-->
      </ul>
      <!--signup and login glyphicons on right of navbar-->
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
          <%= link_to "Profile", profile_path, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Event Planner></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "application-print", :media => "print" %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="container-fluid text-center sm_header">
  <h1>About Us</h1>
</div>
<section class="md_section">
  <div class="container">
    <div class="row">
    </div>
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3" id="about_stuff">
        <p>The social planner web app is
        designed to help students plan social events. It
        is built using the ruby on rails framework along
        with various APIs and deployed through heroku.</p>
      </div>
    </div>
</section>

app/views/static_pages/calendar.html.erb
<div class="container-fluid text-center sm_header">
  <h1>Calendar</h1>
</div>
<section class="md_section">
  <div id='calendar'></div>
</section>

app/views/static_pages/contact.html.erb
<div class="container-fluid text-center sm_header">
  <h1>Contact Us</h1>
</div>
<section class="md_section">
  <div class="container">

    <div class="row">
  		<div class="col-md-8 col-md-offset-2">
  			<div class="cform" id="contact-form">
  				<form role="form" class="contactForm">
  				  <div class="form-group">
  					<label for="name">Your Name</label>
  					<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="maxlen:4" data-msg="Please enter at least 4 chars" />
  					<div class="validation"></div>
  				  </div>
  				  <div class="form-group">
  					<label for="email">Your Email</label>
  					<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
  					<div class="validation"></div>
  				  </div>
  				  <div class="form-group">
  					<label for="subject">Subject</label>
  					<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="maxlen:4" data-msg="Please enter at least 8 chars of subject" />
  					<div class="validation"></div>
  				  </div>
  				  <div class="form-group">
  					<label for="message">Message</label>
  					<textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us"></textarea>
  					<div class="validation"></div>
  				  </div>

  				  <button type="submit" class="btn btn-theme pull-left">SEND MESSAGE</button>
  				</form>

  			</div>
  		</div>
  		<!-- ./span12 -->
  	</div>
  </div>
</section>

app/views/static_pages/events.html.erb
<div class="container-fluid text-center sm_header">
  <h1>Events</h1>
</div>
<section class="md_section">
  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
</section>

app/views/static_pages/groups.html.erb
<div class="container-fluid text-center sm_header">
  <h1>Groups</h1>
</div>
<section class="md_section">
</section>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<%= render 'layouts/homeheader' %>
<% end %>

app/views/static_pages/profile.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<div class="container">
    <div class="fb-profile">
        <img align="left" class="fb-image-lg" src="http://lorempixel.com/850/280/nightlife/5/" alt="Profile image example"/>
        <img align="left" class="fb-image-profile thumbnail" src="http://lorempixel.com/180/180/people/1/" alt="Profile image example"/>
        <div class="fb-profile-text">
            <h1><%= User.find(current_user)[:email] %></h1>
            <p>This app is a lot of work!</p>
        </div>
    </div>
</div> <!-- /container -->

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>